# Generated by Django 6.0 on 2025-12-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_app', '0002_inscricao_certificado_liberado_alter_evento_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner do Evento'),
        ),
    ]
