# Generated by Django 6.0 on 2025-12-07 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_app', '0003_evento_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizador_responsavel',
            field=models.ForeignKey(limit_choices_to={'perfil__in': ['ORGANIZADOR', 'PROFESSOR']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instituicao_ensino',
            field=models.CharField(blank=True, help_text='Instituição de ensino', max_length=100, null=True),
        ),
    ]
