# Generated by Django 6.0 on 2025-12-07 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_app', '0004_alter_evento_organizador_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO_USUARIO', 'Criação de Usuário'), ('LOGIN', 'Login no Sistema'), ('EVENTO_CRIAR', 'Cadastro de Evento'), ('EVENTO_EDITAR', 'Alteração de Evento'), ('EVENTO_EXCLUIR', 'Exclusão de Evento'), ('INSCRICAO', 'Inscrição em Evento'), ('CANCELAMENTO', 'Cancelamento de Inscrição'), ('CERTIFICADO_GERAR', 'Geração de Certificado'), ('API_CONSULTA', 'Consulta via API')], max_length=50)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
